### PR TITLE
Return nil lookupMapping if type conversion is not in range for lookup key

### LINKED ISSUE #10233: Lookup Join returns incorrect result due to out-of-range key conversion
Dear Dolt Developers,
I encountered an unexpected execution result in Dolt and would greatly appreciate it if you could take a look. Let's make concerted efforts in enhancing the robustness of Dolt. Thank you very much!
```sql
CREATE  TABLE  t0(c0 BOOLEAN , c1 INT , c2 VARCHAR(500) , c3 BOOLEAN );
CREATE  TABLE  t1(c0 INT , c1 BOOLEAN , c2 BOOLEAN);
CREATE INDEX t0i0 ON t0 (c3 , c2 ) ;


INSERT INTO t1(c2, c0, c1) VALUES (true, true, true);
INSERT INTO t1(c1, c2, c0) VALUES ('', false, false);
INSERT INTO t1(c2, c1, c0) VALUES (true, false, -1);

INSERT INTO t0(c2, c3) VALUES (1, false);
INSERT INTO t0(c3) VALUES (false);

UPDATE t0 SET c3='-128', c1=false;
INSERT INTO t0(c3) VALUES (true);
INSERT INTO t0(c1, c0) VALUES (10, '');
INSERT INTO t0(c0, c1) VALUES ('', -16);
INSERT INTO t0(c2, c3, c0) VALUES ('', true, false);
INSERT INTO t0(c0) VALUES (false);
INSERT INTO t0(c2, c1) VALUES (true, false);
INSERT INTO t0(c1) VALUES (1), (4), ('');



SELECT * FROM t1 INNER  JOIN t0 ON ((t0.c3)<=>(-87840));
-- 6 rows
SELECT * FROM t0 INNER  JOIN t1 ON ((t0.c3)<=>(-87840));
-- 6 rows
SELECT /*+ JOIN_ORDER(t0, t1)*/ * FROM t1 INNER  JOIN t0 ON ((t0.c3)<=>(-87840));
-- 0 rows
```
Adding query hint shouldn't affect query result

Commit: [9571842](https://github.com/dolthub/dolt/commit/9571842973eca3bc8ec04b3d236d52a230a3519c)

### PR DESCRIPTION
**Pull request by angelamayxie**
fixes #10233

Not checking if a value is in the converted range was causing us to use incorrect keys. For example, if the literal `-87840` was used as a key for a boolean/tinyint column, it would get converted to `-128` and match rows with `-128`, even though that's not the same value.

This change checks for if a conversion is `InRange`, and if it's not, it returns a nil `lookupMapping`. The nil `lookupMapping` will then return false when `*lookupMapping.valid()` is called.

Test added in dolthub/go-mysql-server#3357

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@angelamayxie __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9237892</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9237892</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@angelamayxie __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>37519e2</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>37519e2</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/kvexec/lookup_join.go [hunk 1]
```diff
@@ -253,12 +253,12 @@ func newLookupKeyMapping(
 	litTb := val.NewTupleBuilder(litDesc, ns)
 	for i, j := range litMappings {
 		colTyp := typs[j]
-		val, _, err := convertLiteralKeyValue(ctx, colTyp, keyExprs[j].(*expression.Literal))
+		value, err := convertLiteralKeyValue(ctx, colTyp, keyExprs[j].(*expression.Literal))
```
Comment (zachmu) [inline go/libraries/doltcore/sqle/kvexec/lookup_join.go]: Strikes me as the wrong fix. If the literal is out of range for the target type, we know the lookup will return no rows. We could communicate this to the call site of this function and let them deal with it appropriately by returning an empty result, which is how this works in GMS's join / index lookup logic. Same thing should happen here.

**Review by zachmu — COMMENTED** [review]
Probably should use the same logic for this that GMS does, this seems like it was just an oversight when the latest round of bug fixes for this problem were just applied ther.

**Comment by coffeegoddd** [comment]
@angelamayxie __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4ff5e11</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4ff5e11</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@angelamayxie __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b80ef45</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b80ef45</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
