### PR TITLE
Fix panic during merge when FK is dropped and re-added on a branch with a composite PK child table

### LINKED ISSUE #10676: Panic attempting to merge : index out of range [1] with length 1
I'm trying to merge from main, main has had some constraint changes, including a commit which drops constraints and another that adds constraints.

I get a panic, its the same if i rebase, see below.

What worked though was merging each commit, one at a time, then there was no issue. I believe it's something to do with the constraints needing to be separately dropped and then added.

```
❯ dolt merge origin/main
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/merge.foreignKeysAreCompatibleTypes(0x10b90f600?, 0x20bb59c9f3e0)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/violations_fk_prolly.go:379 +0xc4
github.com/dolthub/dolt/go/libraries/doltcore/merge.prollyChildPriDiffFkConstraintViolations({0x10a193be0, 0x20bb3839e5a0}, {{0x20bb36f37080, 0x1c}, {{0x20bb6d151b78, 0x13}, {0x0, 0x0}}, {0x20bb36f370e0, 0x1c}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/violations_fk_prolly.go:256 +0x1fc
github.com/dolthub/dolt/go/libraries/doltcore/merge.childFkConstraintViolations({0x10a193be0, 0x20bb3839e5a0}, {{0x20bb36f37080, 0x1c}, {{0x20bb6d151b78, 0x13}, {0x0, 0x0}}, {0x20bb36f370e0, 0x1c}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/violations_fk.go:342 +0x188
github.com/dolthub/dolt/go/libraries/doltcore/merge.RegisterForeignKeyViolations(0x20bb3839e5a0, {0x10a17cc40, 0x20bb3839edc0}, {0x10a24aa00, 0x20bb37df6d80}, {0x10a24aa00, 0x20bb3f212ba0}, 0x0, {0x10a18ea20, 0x20bb37a9c420})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/violations_fk.go:138 +0x670
github.com/dolthub/dolt/go/libraries/doltcore/merge.AddForeignKeyViolations(0x20bb3839e5a0, {0x10a17cc40, 0x20bb3839edc0}, {0x10a24aa00, 0x20bb37df6d80}, {0x10a24aa00, 0x20bb3f212ba0}, 0x0, {0xa4, 0x29, ...})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/violations_fk.go:156 +0x134
github.com/dolthub/dolt/go/libraries/doltcore/merge.MergeRoots(0x20bb3839e5a0, {0x10a17cc40, 0x20bb3839edc0}, {0x10a24aa00, 0x20bb3f212960}, {0x10a24aa00, 0x20bb3f2129c0}, {0x10a24aa00, 0x20bb3f212ba0}, {0x10a179a60, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge.go:369 +0xe80
github.com/dolthub/dolt/go/libraries/doltcore/merge.MergeCommits(0x20bb3839e5a0, {0x10a17cc40, 0x20bb3839edc0}, 0x20bb38350a40, 0x20bb38350b80, {0x70?})
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge.go:86 +0x120
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.executeMerge(0x20bb3839e5a0, 0x20bb3b7862d0, {0x20bb37b7a1f9, 0x4}, 0x0, 0x0, 0x20bb38350a40, 0x20bb38350b80, {0x20bb3f1df850, 0xb}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_merge.go:347 +0x78
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.performMerge(0x20bb3839e5a0, 0x20bb3b7862d0, 0x20bb37a7f310, {0x20bb37b7a1f9, 0x4}, 0x20bb36fc2f00, 0x0, {0x20bb37bbcec0, 0x37}, 0x0)
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_merge.go:289 +0x654
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.doDoltMerge(0x20bb3839e5a0, {0x20bb3f1fd500, 0x3, 0x3})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_merge.go:183 +0x854
github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.doltMerge(0x20bb3f1efec8?, {0x20bb3f1fd500?, 0x0?, 0x0?})
        github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures/dolt_merge.go:82 +0x24
reflect.Value.call({0x109b030e0?, 0x10a1372a0?, 0x0?}, {0x10723d126, 0x4}, {0x20bb38421bc0, 0x4, 0x1099bc0c0?})
        reflect/value.go:586 +0xabc
reflect.Value.Call({0x109b030e0?, 0x10a1372a0?, 0x10a24c1d8?}, {0x20bb38421bc0?, 0x1099bc0c0?, 0x20bb38c58d80?})
        reflect/value.go:369 +0x94
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildExternalProcedure(0x20bb3f1f06c8?, 0x20bb3839e5a0, 0x20bb378acf50, {0x109e2e840?, 0x5001f0718?, 0x10f89e6f8?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/rel.go:737 +0x37c
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x20bb391fc0e0, 0x10?, {0x10a1acca0?, 0x20bb378acf50}, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:160 +0x114
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x20bb391fc0e0?, 0x20bb3839e5a0?, {0x10a1acca0, 0x20bb378acf50}, {0x0?, 0x0?, 0x0?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:36 +0x98
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildProcedure(0x20bb3f1f09b8?, 0x104ebd0dc?, 0xb?, {0x0?, 0xf001f09d8?, 0x10f739cc0?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/rel.go:346 +0x38
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x20bb391fc0e0, 0x104e5a36c?, {0x10a1aa270?, 0x20bb391fce00}, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:248 +0x1e50
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x20bb391fc0e0?, 0x20bb3839e5a0?, {0x10a1aa270, 0x20bb391fce00}, {0x0?, 0x0?, 0x0?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:36 +0x98
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildCall(0x20bb391fc0e0, 0x20bb3839e5a0, 0x20bb374f91e0, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/proc.go:202 +0x7a4
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExecNoAnalyze(0x20bb391fc0e0, 0x1067aba58?, {0x10a1aa108?, 0x20bb374f91e0}, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:110 +0x2a50
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).buildNodeExec(0x20bb391fc0e0?, 0x20bb3839e5a0?, {0x10a1aa108, 0x20bb374f91e0}, {0x0?, 0x0?, 0x0?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/node_builder.gen.go:36 +0x98
github.com/dolthub/go-mysql-server/sql/rowexec.(*BaseBuilder).Build(0x20bb391fc0e0, 0x20bb3839e5a0, {0x10a1aa108, 0x20bb374f91e0}, {0x0, 0x0, 0x0})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/sql/rowexec/builder.go:50 +0x9c
github.com/dolthub/go-mysql-server.(*Engine).QueryWithBindings(0x20bb38420600, 0x20bb3839e5a0, {0x20bb3a67c280, 0x4e}, {0x0, 0x0}, 0x0, 0x0)
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/engine.go:385 +0x384
github.com/dolthub/go-mysql-server.(*Engine).Query(0x10724288e?, 0x106f8d770?, {0x20bb3a67c280?, 0x20bb3f1f12c8?})
        github.com/dolthub/go-mysql-server@v0.20.1-0.20260311211816-cacba544a39e/engine.go:195 +0x30
github.com/dolthub/dolt/go/cmd/dolt/commands/engine.(*SqlEngine).Query(0x20bb37d804b0?, 0x10a1a14e0?, {0x20bb3a67c280?, 0x20bb37bc6d20?})
        github.com/dolthub/dolt/go/cmd/dolt/commands/engine/sqlengine.go:456 +0x24
github.com/dolthub/dolt/go/cmd/dolt/commands.MergeCmd.Exec({}, {0x10a194598, 0x20bb37c94f00}, {0x20bb37b77cd0, 0xa}, {0x20bb36e543e0, 0x1, 0x1}, 0x20bb379d2320?, {0x10a1a14e0, ...})
        github.com/dolthub/dolt/go/cmd/dolt/commands/merge.go:135 +0x30c
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.handleCommand({{0x10db24a00, 0x10}, {0x20bb36eb5008, 0x20bb379d2310}, {0x20bb37c9d728, 0x104e5a36c}, {0x10, 0x109c8ce20, 0x30}, 0x80}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:255 +0x2d0
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec({{0x10723ceae, 0x4}, {0x1072617af, 0x11}, {0x0, 0x0}, {0x10b9c4ba0, 0x39, 0x39}, 0x0}, ...)
        github.com/dolthub/dolt/go/cmd/dolt/cli/command.go:210 +0x1e8
main.runMain()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:551 +0x2490
main.main()
        github.com/dolthub/dolt/go/cmd/dolt/dolt.go:208 +0x3c
```

### PR DESCRIPTION
**Pull request by elianddb**
Fix #10676 
`dolt merge` could panic with `index out of range` when one branch dropped and re-added a foreign key (creating a new backing index) while the other branch had new rows in a child table with a composite primary key. This fix limits the FK column type compatibility check to only the columns relevant to the foreign key, ignoring extra primary key columns that are not part of the FK relationship.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.58         | 0.56       | -3.45          |
| groupby_scan         | 10.09        | 10.09      | 0.0            |
| index_join           | 1.86         | 1.86       | 0.0            |
| index_join_scan      | 1.39         | 1.42       | 2.16           |
| index_scan           | 21.89        | 22.28      | 1.78           |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.53         | 0.54       | 1.89           |
| select_random_ranges | 0.55         | 0.56       | 1.82           |
| table_scan           | 21.89        | 21.89      | 0.0            |
| types_table_scan     | 66.84        | 65.65      | -1.78          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.13         | 3.13       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.91       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>2674a18</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>2674a18</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 24e549c548e14ebe886fa14ce8f17647301d3142 | 38.17    | dolt           | bda18ff42abd0bd783caf736c0d626cf73ec1d6c | 37.61  | -1.47          |

File: go/libraries/doltcore/merge/violations_fk_prolly.go [hunk 1]
```diff
@@ -372,17 +386,35 @@ func prollyChildSecDiffFkConstraintViolations(
 	return nil
 }
 
-// foreignKeysAreCompatibleTypes returns whether the serializations for two tuple descriptors are binary compatible
-func foreignKeysAreCompatibleTypes(keyDescA, keyDescB *val.TupleDesc) bool {
-	compatibleTypes := true
-	for i, handlerA := range keyDescA.Handlers {
-		handlerB := keyDescB.Handlers[i]
+// fkIndexKeyDescsAreSerializationCompatible reports whether the type serializations of two tuple descriptors
```
Comment (angelamayxie) [inline go/libraries/doltcore/merge/violations_fk_prolly.go]: this comment is way too long. also don't reference the issue.

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go [hunk 2]
```diff
@@ -3209,6 +3209,61 @@ var MergeScripts = []queries.ScriptTest{
 			},
 		},
 	},
+	{
+		// https://github.com/dolthub/dolt/issues/10676
+		// Merging when one branch drops a FK constraint + its backing index and then re-adds the FK
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go]: remove this description. just link the issue.

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go [hunk 3]
```diff
@@ -3209,6 +3209,61 @@ var MergeScripts = []queries.ScriptTest{
...
+			`CALL DOLT_CHECKOUT('other_branch');`,
+			`INSERT INTO child VALUES (1, 2, 1);`,
+			`CALL DOLT_COMMIT('-Am', 'add child row on other branch');`,
+		},
+		Assertions: []queries.ScriptTestAssertion{
+			{
+				Query:    "CALL DOLT_MERGE('main')",
+				Expected: []sql.Row{{doltCommit, 0, 0, "merge successful"}},
+			},
+			// All parent rows from both branches must be present.
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go]: this comment should be inside the brackets, above the `Expected` line

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go [hunk 4]
```diff
@@ -3209,6 +3209,61 @@ var MergeScripts = []queries.ScriptTest{
...
+			{
+				Query:    "SELECT pk FROM parent ORDER BY pk;",
+				Expected: []sql.Row{{1}},
+			},
+			// All child rows from both branches must survive the merges.
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go]: same here

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go [hunk 5]
```diff
@@ -3209,6 +3209,61 @@ var MergeScripts = []queries.ScriptTest{
...
+			{
+				Query:    "SELECT pk1, pk2, fk_col FROM child ORDER BY pk1, pk2;",
+				Expected: []sql.Row{{1, 1, 1}, {1, 2, 1}},
+			},
+			// The re-added FK constraint (fk2) must still be enforced after the merge.
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go]: same here

**Review by angelamayxie — APPROVED** [review]
looks good except fix the comments

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>2b376c5</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>2b376c5</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>bda18ff</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>bda18ff</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by jycor — APPROVED** [review]
LGTM
