### PR TITLE
go: sqle/dprocedures: fetch,pull,push: Rebase the remote database before we interact with it.

### LINKED ISSUE #9164: push/pull synchronization fails with file remote in multi-node setup
A customer reported an issue that changes pushed to a file-based remote do not propagate consistently across nodes. This is reproducible both in the Dolt Workbench and via MySQL client, Workbench uses the same DOLT_PUSH/DOLT_PULL procedures.

Reproduction Steps:

1. Clone the customer's repo: https://github.com/silldr1/Dolt_Distributed
 
2. Start Docker containers:`docker compose -f docker-compose.yml up -d`
 
3. Connect to each node: 
 - Local Node:
`mysql -h 127.0.0.1 -P 3307 -u "Local Node" -ppassword dolt`
 - Node1:
 `mysql -h 127.0.0.1 -P 3309 -u "node1" -ppassword dolt`
 - Node2:
 `mysql -h 127.0.0.1 -P 3310 -u "node2" -ppassword dolt`

4. On Local Node, create table, commit and push:
```sql
CREATE TABLE test (pk INT);  
CALL dolt_add('.');  
CALL dolt_commit('-m', 'create');  
CALL DOLT_PUSH('origin', 'main'); 
```

5. On Node1, pull changes from Local Node, insert, commit and push:
```sql
CALL DOLT_PULL('origin','main');
INSERT INTO test (pk) VALUES (1);  
CALL dolt_commit('-am', 'insert');  
CALL DOLT_PUSH('origin', 'main');
```

6. On Node2, pull changes from remote:
```sql
CALL DOLT_PULL('origin');  
SELECT * FROM test; 
```
changes from Local Node and Node1 are now in Node2:
```
mysql>  select * from test;
+------+
| pk   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)
```

7. Back on Local Node, pull from remote:
`CALL DOLT_PULL('origin', 'main'); `

could not get changes from Node1:
```
+--------------+-----------+-----------------------+
| fast_forward | conflicts | message               |
+--------------+-----------+-----------------------+
|            0 |         0 | Everything up-to-date |
+--------------+-----------+-----------------------+
1 row in set, 1 warning (0.01 sec)
```
```
mysql> select * from test;
Empty set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by reltuk**
We need to rebase a remote in order to see its latest changes.

Fixes #9164.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@reltuk __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>48f26f3</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>48f26f3</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go [hunk 1]
```diff
@@ -85,6 +85,11 @@ func doDoltFetch(ctx *sql.Context, args []string) (int, error) {
 		return 1, err
 	}
 
+	err = srcDB.Rebase(ctx)
+	if err != nil {
+		return 1, fmt.Errorf("failed to rebase remote db: %w", err)
```
Comment (macneale4) [inline go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go:90]: How likely is this to happen? The error message is going to be very confusing to a user. They'll be like: "I was just trying to fetch latest, and now you're trying to rebase the remote db?!?!"

I would suggest something which doesn't use the word "rebase" - something like, "database out of sync. multiple writers in progress" 

Same goes for the other messages below

**Review by macneale4 — APPROVED** [review]
Code change is fine - but the error message is not.

**Comment by coffeegoddd** [comment]
@reltuk __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>501f174</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>501f174</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
