### PR TITLE
Fix panic merging a changed unique index

### LINKED ISSUE #10753: Panic attempting to merge: byte slice is not of expected size
I think this is similar to #10676, which I reported last week and it was fixed in 1.83.7. I'm on 1.84.0, with a new panic which seems related.

Again I have a commit which adds a field into a unique index and also adds data which would not have been accepted under the old version of the index. And i get this panic:

```
❯ dolt merge m959398v30fv1sr7qkjikl45fkoo8cmq
panic: byte slice is not of expected size

goroutine 200 [running]:
github.com/dolthub/dolt/go/store/val.expectSize(...)
        github.com/dolthub/dolt/go/store/val/codec.go:675
github.com/dolthub/dolt/go/store/val.readInt8(...)
        github.com/dolthub/dolt/go/store/val/codec.go:231
github.com/dolthub/dolt/go/store/val.compare({0xf8?, 0x70?}, {0x64b0f48561a1?, 0x1?, 0x0?}, {0x64b0fba1a917, 0x25, 0x1069})
        github.com/dolthub/dolt/go/store/val/tuple_compare.go:102 +0x1644
github.com/dolthub/dolt/go/store/val.(*DefaultTupleComparator).CompareValues(...)
        github.com/dolthub/dolt/go/store/val/tuple_compare.go:70
github.com/dolthub/dolt/go/libraries/doltcore/schema.collationCompare({0x64b0fba1a8b6?, 0x3348d06245d669a?}, {0x0?, 0x97?}, 0xfb59?, {0x64b0f48561a1?, 0x64b0f42f1200?, 0x64b0fb587140?}, {0x64b0fba1a917?, 0x10530ac60?, ...})
        github.com/dolthub/dolt/go/libraries/doltcore/schema/collation_comparator.go:116 +0x98
github.com/dolthub/dolt/go/libraries/doltcore/schema.CollationTupleComparator.Compare({{0x64b0fb58de40?, 0x1052fd828?, 0x64b0fb587258?}}, {0x1097cdde0, 0x64b0fab30dc0}, {0x64b0f4856140, 0x97, 0x97}, {0x64b0fba1a8b6, 0x97, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/schema/collation_comparator.go:49 +0x278
github.com/dolthub/dolt/go/store/val.(*TupleDesc).Compare(0x623f90d5c15bd697?, {0x1097cdde0?, 0x64b0fab30dc0?}, {0x64b0f4856140?, 0x1097cdde0?, 0x64b0fab30dc0?}, {0x64b0fba1a8b6?, 0x1052190cc?, 0x64b0fb5873b8?})
        github.com/dolthub/dolt/go/store/val/tuple_descriptor.go:186 +0x3c
github.com/dolthub/dolt/go/store/prolly/tree.newLeafCursorAtKey[...]({0x1097cdde0, 0x64b0fab30dc0}, {0x1098662e8, 0x64b0f47e7800}, 0x1044558c8, {0x64b0f4856140?, 0x97, 0x97}, 0x64b0fb5bbda0)
        github.com/dolthub/dolt/go/store/prolly/tree/node_cursor.go:194 +0x108
github.com/dolthub/dolt/go/store/prolly/tree.StaticMap[...].GetPrefix(0x109889900?, {0x1097cdde0?, 0x64b0fab30dc0?}, {0x64b0f4856140?, 0x97, 0x97}, 0x64b0fb5bbda0, 0x64b0fb566980)
        github.com/dolthub/dolt/go/store/prolly/tree/map.go:263 +0x7c
github.com/dolthub/dolt/go/store/prolly/tree.MutableMap[...].GetPrefix(0x109885840, {0x1097cdde0, 0x64b0fab30dc0}, {0x64b0f4856140, 0x97, 0x97}, 0x64b0fb5bbda0, 0x64b0fb566980)
        github.com/dolthub/dolt/go/store/prolly/tree/mutable_map.go:65 +0x104
github.com/dolthub/dolt/go/store/prolly.(*GenericMutableMap[...]).GetPrefix(...)
        github.com/dolthub/dolt/go/store/prolly/tuple_mutable_map.go:145
github.com/dolthub/dolt/go/libraries/doltcore/merge.uniqIndex.findCollisions({{0x1098779a0, 0x64b0f740dd40}, 0x64b0fb5bbe00, 0x64b0fb5bbe60, 0x64b0fb5bbda0, 0x64b0fb5bbc20, {{0x64b0f762d6c0, 0x7, 0x7}, {0x64b0f75a6ab0, ...}}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:984 +0x1ec
github.com/dolthub/dolt/go/libraries/doltcore/merge.uniqValidator.validateDiff({{0x1097b3ac0, 0x64b0f5757440}, {0xb2, 0x4a, 0x91, 0xa5, 0x1f, 0x18, 0x1f, 0xf0, ...}, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:820 +0x438
github.com/dolthub/dolt/go/libraries/doltcore/merge.computeProllyTreePatches(0x64b0fab30dc0, 0x64b0f41a36c0, {0x109874f90, 0x64b0f467db00}, 0x64b0fab63160, 0x64b0fabeac60, {0x58?, 0x4f?, 0x7a?}, {0xf5?, ...}, ...)
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:327 +0xd68
github.com/dolthub/dolt/go/libraries/doltcore/merge.mergeProllyTableData.func1()
        github.com/dolthub/dolt/go/libraries/doltcore/merge/merge_prolly_rows.go:453 +0x54
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.19.0/errgroup/errgroup.go:93 +0x4c
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        golang.org/x/sync@v0.19.0/errgroup/errgroup.go:78 +0x90
```

I will try as a workaround rebasing into 2 separate commits and merging them one at a time

### PR DESCRIPTION
**Pull request by elianddb**
When a unique index's definition changed on one branch (e.g. a column was added to it), merging would panic with `byte slice is not of expected size`. This happened because the uniqueness checker loaded the index's old binary data and tried to read it under the new schema's layout.
- Unique constraint violations produced by the changed index are now surfaced as inspectable conflict artifacts.

Fix dolthub/dolt#10753

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.55         | 0.55       | 0.0            |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.79         | 1.86       | 3.91           |
| index_join_scan      | 1.34         | 1.37       | 2.24           |
| index_scan           | 22.28        | 22.69      | 1.84           |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.53         | 0.53       | 0.0            |
| select_random_ranges | 0.55         | 0.56       | 1.82           |
| table_scan           | 22.28        | 22.69      | 1.84           |
| types_table_scan     | 68.05        | 68.05      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.43         | 6.32       | -1.71          |
| oltp_insert           | 3.07         | 3.13       | 1.95           |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.91       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>439e53e</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>439e53e</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 58.92            | 61.08          | 3.67           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | dd32a3c14dfd7d50b669482180b475679e82a6c2 | 41.97    | dolt           | 4a6723fcc8d0b71095bcd570f70b72bbe634f016 | 37.56  | -10.51         |

File: go/libraries/doltcore/merge/mutable_secondary_index.go [hunk 1]
```diff
@@ -80,11 +81,15 @@ func GetMutableSecondaryIdxsWithPending(ctx *sql.Context, ns tree.NodeStore, our
 		// TODO: This isn't technically required, but correctly handling updating secondary indexes when only some
 		// of the table's rows have been updated is difficult to get right.
 		// Dropping the index is potentially slower but guaranteed to be correct.
+		ourIndex := ourSch.Indexes().GetByName(index.Name())
```
Comment (angelamayxie) [inline go/libraries/doltcore/merge/mutable_secondary_index.go]: the `ourSch` and `ourIndex` naming convention is weird to me...what are they supposed to be referring to?

also, shouldn't these new lines go above the TODO comment?

**Review by jycor — APPROVED** [review]
LGTM

File: go/libraries/doltcore/merge/mutable_secondary_index.go (hunk 1 above)
Comment (jycor) [reply go/libraries/doltcore/merge/mutable_secondary_index.go]: I believe this is using Git's "ours" vs "theirs" naming when merging a feature branch into the current branch.

Comment (elianddb) [reply go/libraries/doltcore/merge/mutable_secondary_index.go]: Ye Git semantics ours is the left branch and theirs is the right. I've moved the lines above the todo too.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4a6723f</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4a6723f</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by angelamayxie — APPROVED** [review]
