### PR TITLE
#9508 - Fix dolt_log table function to support bind variables in prepared statements

### LINKED ISSUE #9508: can't prepare dolt_log procedure statement
When building prepared statement using dolt_log and variables for the from and to commits in a 2-dot style query, we get an unbound variable error.
```
mysql> prepare stmt1 from 'select * from dolt_log(?, \'--not\', ?)';
ERROR 1105 (HY000): unbound variable "v1" in query
```

### PR DESCRIPTION
**Pull request by elianddb**
Fixes #9508
Fix dolt_log table function to support bind variables in prepared statements
Implemented deferred argument parsing to allow proper bind variable handling during prepare phase

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>62431f1</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>62431f1</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>33d4d83</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>33d4d83</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7e4d175</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7e4d175</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 1]
```diff
@@ -209,6 +213,10 @@ func (ltf *LogTableFunction) CheckAuth(ctx *sql.Context, opChecker sql.Privilege
 
 // Expressions implements the sql.Expressioner interface.
 func (ltf *LogTableFunction) Expressions() []sql.Expression {
+	// Always return the original argument expressions from deferred parsing
+	if ltf.argumentExprs != nil {
+		return ltf.argumentExprs
+	}
 	return []sql.Expression{}
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: You should be able to just `return ltf.argumentExprs` inside this function, without any of the other lines. Go will treat `nil` and an empty slice the same, so no need for the other lines.

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 2]
```diff
@@ -280,16 +288,21 @@ func (ltf *LogTableFunction) addOptions(expression []sql.Expression) error {
...
 
 func (ltf *LogTableFunction) WithExpressions(exprs ...sql.Expression) (sql.Node, error) {
-	if len(exprs) != 0 {
-		return nil, sql.ErrInvalidChildrenNumber.New(0, len(exprs))
+	// Always use deferred parsing approach - this handles both bind variables and literals
+	if len(exprs) == 0 {
+		return ltf, nil
 	}
-	return ltf, nil
+	return ltf.evalArguments(exprs...)
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: `With...` methods in `sql.Node` should always return a copy and shouldn't do any work (i.e. shouldn't eval expressions) – this is because `With...` functions may be called many times during analysis while the query plan is transformed, so doing work here can be wasteful and in some cases can lead to incorrect execution. 

This file has some odd code in it from before you started making your changes, so might be best to spend some time together looking at that, otherwise it may be hard to know what's a good pattern in this existing code and what's not good.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7de6f23</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7de6f23</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0def044</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0def044</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>2f13076</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>2f13076</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9deed4e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9deed4e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>a60ff2b</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>a60ff2b</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>764d430</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>764d430</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>eecae87</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>eecae87</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: integration-tests/bats/system-tables.bats [hunk 3]
```diff
@@ -1062,3 +1062,109 @@ SQL
...
+    [[ "$output" =~ "1" ]] || false  # Should have 1 commit in the range
+    
+    # Test the original customer issue: dolt_log with --not flag and bind variables
+    run dolt sql -q "prepare stmt3 from 'select count(*) from dolt_log(?, \"--not\", ?)'; set @v1 = 'HEAD', @v2 = 'HEAD~1'; execute stmt3 using @v1, @v2;"
+    [ "$status" -eq 0 ]
+    [[ "$output" =~ "1" ]] || false  # Should have 1 commit (HEAD excluding HEAD~1)
+    
+    # Test bind variables with other flags
+    run dolt sql -q "prepare stmt4 from 'select commit_hash from dolt_log(?, \"--parents\")'; set @v1 = 'HEAD'; execute stmt4 using @v1;"
+    [ "$status" -eq 0 ]
```
Comment (fulghum) [inline integration-tests/bats/system-tables.bats]: (minor) if you don't care about checking results and just want to assert that a command ran successfully, you can just use the command (without the `run` keyword) and the script will fail automatically if that command fails. 

```suggestion
    dolt sql -q "prepare stmt4 from 'select commit_hash from dolt_log(?, \"--parents\")'; set @v1 = 'HEAD'; execute stmt4 using @v1;"
```

File: integration-tests/bats/system-tables.bats [hunk 4]
```diff
@@ -1062,3 +1062,109 @@ SQL
...
+    dolt commit -m "Changed Alice to Bob"
+    
+    dolt checkout main
+    dolt sql -q "update users set name = 'Charlie' where id = 1"
+    dolt add users
+    dolt commit -m "Changed Alice to Charlie"
+    
+    # Test dolt_preview_merge_conflicts with bind variables (should work)
+    # NOTE: dolt_preview_merge_conflicts is a dynamic table function but supports bind variables
+    # because it has !expression.IsBindVar() checks in its WithExpressions method
```
Comment (fulghum) [inline integration-tests/bats/system-tables.bats]: This line is confusing, I think you should just delete it. Reading this, it sounds like `WithExpressions` has a `!expression.IsBindVar()` check, as in it asserts that the expressions are not bind vars, but that's not what the code is doing. I think you can just delete this last line and keep it simple. 
```suggestion
```

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 5]
```diff
@@ -14,11 +14,16 @@
 
 package dtablefunctions
 
+// This table function violates SQL analyzer principles by evaluating expressions
+// during both analysis and execution phases. This is necessary because CLI
+// arguments requires pre-evaluated strings for schema determination. Bind variables
+// are handled by skipping evaluation during analysis and deferring to execution.
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: I think you can move this down to the `evalArguments` function, or somewhere else nearby where the expressions are eval'ed. Also, so some minor changes suggested: 
```suggestion
// This table function violates SQL analyzer principles by evaluating expressions
// during analysis. This is necessary because the schema changes based on what
// arguments are supplied (e.g. --parent), and the schema needs to be known 
// during analysis time. Bind variables are skipped over during the initial analysis of 
// the prepared statement, and get fully resolved when they are bound when the 
// prepared statement is later executed.
```

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 6]
```diff
@@ -515,41 +530,34 @@ func (ltf *LogTableFunction) RowIter(ctx *sql.Context, row sql.Row) (sql.RowIter
...
-				refs := strings.Split(valStr, "...")
-				return refs, nil, true, nil
-			}
-			refs := strings.Split(valStr, "..")
-			return []string{refs[1]}, []string{refs[0]}, false, nil
+// parseRevisionRange processes a revision string for range syntax (.., ...)
+// Returns (revisions, notRevisions, threeDot, isRange)
+func parseRevisionRange(revisionStr string) ([]string, []string, bool, bool) {
+	if strings.Contains(revisionStr, "..") {
+		if strings.Contains(revisionStr, "...") {
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: Looks like a copy/paste error here?

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 7]
```diff
@@ -515,41 +530,34 @@ func (ltf *LogTableFunction) RowIter(ctx *sql.Context, row sql.Row) (sql.RowIter
...
-		if strings.Contains(valStr, "..") {
-			if strings.Contains(valStr, "...") {
-				refs := strings.Split(valStr, "...")
-				return refs, nil, true, nil
-			}
-			refs := strings.Split(valStr, "..")
-			return []string{refs[1]}, []string{refs[0]}, false, nil
+// parseRevisionRange processes a revision string for range syntax (.., ...)
+// Returns (revisions, notRevisions, threeDot, isRange)
+func parseRevisionRange(revisionStr string) ([]string, []string, bool, bool) {
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: A nice feature of Go is that you can name return values. That provides more context to callers on what is being returned, and IDEs will use it to generate variable names, etc. If you add the return var names from your godocs to the return var section in your function signature, then you won't need to mention them in the docstring, and they'll actually end up being more useful.

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 8]
```diff
@@ -515,41 +530,34 @@ func (ltf *LogTableFunction) RowIter(ctx *sql.Context, row sql.Row) (sql.RowIter
...
-		notValStr, err := expressionToString(ltf.ctx, notExpr)
-		if err != nil {
-			return nil, nil, false, err
-		}
-
-		if strings.HasPrefix(notValStr, "^") {
-			notValStr = strings.TrimPrefix(notValStr, "^")
+// evaluateArguments returns revisionValStrs, notRevisionValStrs, and three dot boolean.
+// It processes the stored revision strings from the CLI parser and handles range syntax.
+func (ltf *LogTableFunction) evaluateArguments() (revisionValStrs []string, notRevisionValStrs []string, threeDot bool, err error) {
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: It's a little messy to have a function called `evaluateArguments()` and another function in the same type called `evalArguments()`. That makes it hard for readers to understand the difference and when to use each. See if you can clean that up and give each a good, self-documenting name that makes them easy to distinguish, even if someone hasn't read the function documentation.

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 9]
```diff
@@ -515,41 +530,34 @@ func (ltf *LogTableFunction) RowIter(ctx *sql.Context, row sql.Row) (sql.RowIter
...
+		if revs, notRevs, isThreeDot, isRange := parseRevisionRange(revisionStr); isRange {
+			return revs, notRevs, isThreeDot, nil
 		}
-
-		notRevisionValStrs = append(notRevisionValStrs, notValStr)
+		revisionValStrs = append(revisionValStrs, revisionStr)
 	}
 
+	// Process stored not-revision strings
+	notRevisionValStrs = append(notRevisionValStrs, ltf.notRevisionStrs...)
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: This seems a little fishy, too... there's not any "processing" actually going on here, right? We're just making a copy of `ltf.notRevisionStrs`. This feels like we can simplify more here. 

Speaking of simplifying... the `error` return param is never actually used here. Sometimes it's nice to leave room for that in an interface, but for a helper function like this, you should just simplify and not force the caller to check an error if one isn't ever going to be returned. 

Take another look at this code and see how much more you can simplify here.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e4c4b1e</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e4c4b1e</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go [hunk 10]
```diff
@@ -218,6 +228,12 @@ func getDoltArgs(ctx *sql.Context, expressions []sql.Expression, name string) ([
 	var args []string
 
 	for _, expr := range expressions {
+		// Skip bind variables during analysis phase (can't evaluate yet)
+		// During execution phase, bind variables are resolved to literals by SQL engine
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go]: Small suggestion to make this comment a little more exact/accurate:

```suggestion
		// Skip bind variables during prepared statement analysis, since we can't evaluate them.
		// During execution of a prepared statement, bind variables are replaced with eval'able expressions.
```

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b238ab9</TD>
<TD>ok</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b238ab9</TD>
<TD>5937457</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
