### PR TITLE
Fix dolt push failing when remote has ignored tables in working set

### LINKED ISSUE #10727: dolt push fails with 'uncommitted changes' when remote has ignored tables in working set
## Summary

`dolt push` to a remote sql-server fails with "target has uncommitted changes. --force required to overwrite" when the remote's working set contains tables listed in `dolt_ignore`, even though `dolt_status` on the remote reports no uncommitted changes.

This is the same class of bug as #10698 (which affected `dolt_rebase` and was fixed in v1.83.8), but in the `dolt push` codepath.

## Reproduction

```bash
#!/usr/bin/env bash
set -euo pipefail

TESTDIR="/var/tmp/dolt-push-ignore-test"
rm -rf "$TESTDIR"
mkdir -p "$TESTDIR"

cleanup() {
    if [ -n "${SERVER_PID:-}" ]; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

SQL_PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("",0)); print(s.getsockname()[1]); s.close()')
API_PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("",0)); print(s.getsockname()[1]); s.close()')

remote_sql() {
    dolt --host 127.0.0.1 --port "$SQL_PORT" --no-tls sql -q "$1"
}

# Set up remote repo and start sql-server
mkdir "$TESTDIR/remote" && cd "$TESTDIR/remote"
dolt init --name "remote" --email "remote@test"
dolt sql-server \
    --host 127.0.0.1 --port "$SQL_PORT" \
    --remotesapi-port "$API_PORT" \
    --loglevel warning &>"$TESTDIR/server.log" &
SERVER_PID=$!
sleep 2

# Create a table, add it to dolt_ignore, commit
remote_sql "USE remote;
    CREATE TABLE t (id INT PRIMARY KEY);
    INSERT INTO t VALUES (1);
    INSERT INTO dolt_ignore VALUES ('ignored_table', true);
    CALL dolt_add('.');
    CALL dolt_commit('-m', 'Initial commit');"

# Create the ignored table (present in working set, but ignored)
remote_sql "USE remote;
    CREATE TABLE ignored_table (id INT PRIMARY KEY);
    INSERT INTO ignored_table VALUES (1);"

# dolt_status shows clean
echo "Remote dolt_status (expected: empty / clean):"
remote_sql "USE remote; SELECT * FROM dolt_status;"

# Clone, make a new commit, push
cd "$TESTDIR"
dolt clone "http://127.0.0.1:$API_PORT/remote" local 2>&1
cd "$TESTDIR/local"
dolt sql -q "INSERT INTO t VALUES (2)"
dolt add .
dolt commit -m "Second commit"

echo ""
echo "Pushing to remote:"
if dolt push origin main 2>&1; then
    echo "PASS: push succeeded"
else
    echo "FAIL: push rejected due to ignored table in working set"
fi
```

Output:
```
Remote dolt_status (expected: empty / clean):

Pushing to remote:
target has uncommitted changes. --force required to overwrite
FAIL: push rejected due to ignored table in working set
```

Note: if `DOLT_ROOT_PASSWORD` is set in the environment, unset it before starting the test server (the script above assumes no auth).

## Root Cause

Same as #10698: the push codepath compares the remote's working set root hash against the committed root hash. Ignored tables exist in the working set but not in the committed state, so the hashes differ, and the push is rejected as having "uncommitted changes".

`dolt_status` correctly filters out ignored tables, so it reports clean — but the push check doesn't account for them.

## Expected Behavior

`dolt push` should succeed when the only differences in the remote's working set are ignored tables.

## Real-World Impact

This blocks normal push workflows when a production server has `dolt_ignore` entries for tables like `ar_internal_metadata` or session/tracking tables that the application writes to but shouldn't be version-controlled. The only workaround is `--force`, which is undesirable for production remotes.

## Environment

- Dolt version: 1.82.3 (local), 1.82.6 (remote)
- OS: Linux

### PR DESCRIPTION
**Pull request by elianddb**
`dolt push` returned "target has uncommitted changes. --force required to overwrite" when the remote's working set contained tables listed in `dolt_ignore`, even though `dolt status` showed clean. Push now succeeds in this case, consistent with how other commands (rebase, pull, stash) already handle ignored tables.
Fix #10727

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.54         | 0.55       | 1.85           |
| groupby_scan         | 9.73         | 9.73       | 0.0            |
| index_join           | 1.86         | 1.86       | 0.0            |
| index_join_scan      | 1.37         | 1.37       | 0.0            |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.53         | 0.53       | 0.0            |
| select_random_ranges | 0.55         | 0.55       | 0.0            |
| table_scan           | 22.28        | 22.28      | 0.0            |
| types_table_scan     | 65.65        | 66.84      | 1.81           |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.24        | 11.45      | 1.87           |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 5.99         | 5.99       | 0.0            |
| types_delete_insert   | 6.79         | 6.79       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e6bdc52</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e6bdc52</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 7dcc46882ccd1c20edaf55b5f246722d605827d4 | 38.6     | dolt           | 3c5e5b46ef43fbaaca4752ebef8d6fc1fa1a9837 | 38.18  | -1.09          |

File: go/libraries/doltcore/env/actions/remotes.go [hunk 1]
```diff
@@ -89,6 +105,9 @@ func Push(ctx context.Context, tempTableDir string, mode ref.UpdateMode, destRef
 		err = srcDB.SetHeadToCommit(ctx, remoteRef, commit)
 	case ref.FastForwardOnly:
 		err = destDB.FastForwardWithWorkspaceCheck(ctx, destRef, commit)
+		if errors.Is(err, datas.ErrDirtyWorkspace) {
+			err = pushSkippingIgnoredTables(ctx, destDB, destRef, commit)
+		}
 		if err != nil {
```
Comment (jycor) [inline go/libraries/doltcore/env/actions/remotes.go]: Should always check for `WorkingSetContainsOnlyIgnoredTables` instead of only when we error.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b37dcbd</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b37dcbd</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3c5e5b4</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3c5e5b4</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by jycor — APPROVED** [review]
LGTM
