### PR TITLE
Fix `show tables` to show singular name when local table name conflicts with a non-local table name

### LINKED ISSUE #10283: Non-local tables appear twice in `show tables`, dolt workbench.
Hello,

We are using non-local tables described in https://www.dolthub.com/blog/2025-10-06-nonlocal-tables/. You can repro the oddity I'm seeing by simply:

- connect
- create a fresh database, `create database test;`
- create a table, `create table foo ( id int auto_increment primary key );`
- observe that the table is listed once by `show tables`
- make it non-local, with `insert into dolt_nonlocal_tables (table_name, target_ref, options) values ('f*', 'main', 'immediate');`
- observe that the table is now listed TWICE by `show tables`

```
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| foo            |
| foo            |
+----------------+
2 rows in set (0.00 sec)
```

dolt workbench also lists the table table twice, presumably because it does similar things to get a listing of all tables.

Is this expected behaviour?

Cheers,
Luke

### PR DESCRIPTION
**Pull request by elianddb**
Fix dolthub/dolt#10283

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>809cd1a</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>809cd1a</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/database.go [hunk 1]
```diff
@@ -1690,6 +1690,7 @@ func (db Database) GetAllTableNames(ctx *sql.Context, showSystemTables bool) ([]
 func (db Database) getAllTableNames(ctx *sql.Context, root doltdb.RootValue, includeGeneratedSystemTables bool, includeRootObjects bool, includeNonlocalTables readNonlocalTablesFlag) ([]string, error) {
 	var err error
 	var result []string
+	localNameSet := map[string]any{}
```
Comment (jycor) [inline go/libraries/doltcore/sqle/database.go]:
```suggestion
	localNameSet := map[string]struct{}
```

File: go/libraries/doltcore/sqle/database.go [hunk 2]
```diff
@@ -1705,6 +1706,9 @@ func (db Database) getAllTableNames(ctx *sql.Context, root doltdb.RootValue, inc
 		if err != nil {
 			return nil, err
 		}
+		for _, nameStr := range result {
+			localNameSet[nameStr] = nil
```
Comment (jycor) [inline go/libraries/doltcore/sqle/database.go]:
```suggestion
			localNameSet[nameStr] = struct{}{}
```

**Review by jycor — APPROVED** [review]
LGTM

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>b8f00a1</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>b8f00a1</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
