### PR TITLE
Fix `dolt_clean` not respecting `dolt_ignore` and `dolt_nonlocal_tables` patterns

### LINKED ISSUE #10462: dolt_clear() drops Nonlocal Tables
Good day, we are using nonlocal tables in our project. I noticed on the Workbench that the global tables we use are shown as untracked and they are dropped if you clear working changes.

I double checked and am running latest dolt-sql-server v1.81.7

Steps to reproduce:
```
CREATE DATABASE test_nonlocal;
USE test_nonlocal;

# as per https://www.dolthub.com/blog/2025-10-06-nonlocal-tables/
CALL DOLT_CHECKOUT('main');
INSERT INTO dolt_nonlocal_tables (table_name, target_ref, options) VALUES ('global_*', 'main', 'immediate');
INSERT INTO dolt_ignore (pattern, ignored) VALUES ('global_*', true);
CALL DOLT_ADD('dolt_nonlocal_tables', 'dolt_ignore');
# status|
# ------+
#      0|

CALL DOLT_COMMIT('-m', 'set up dolt_nonlocal_tables and dolt_ignore system tables');
# hash                            |
# --------------------------------+
# b04aphfm4di7g2vhtcd67u14h0bu7r06|

SELECT * FROM DOLT_STATUS;
# table_name|staged|status|
# ----------+------+------+
```

All good so far, now create a global table:

```
CREATE TABLE `global_test` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM DOLT_STATUS;
# table_name |staged|status   |
# -----------+------+---------+
# global_test|     0|new table| 

INSERT INTO `global_test` (id, name) VALUES(1, 'one');

CALL DOLT_COMMIT('-A', '-m', 'this should return error as there is nothing to commit');
# SQL Error [1105] [HY000]: nothing to commit

SELECT * FROM `global_test`;
# id|name|
# --+----+
#  1|one |

CALL DOLT_CLEAN();
# status|
# ------+
#      0|

SELECT * FROM `global_test`;
# SQL Error [1146] [42S02]: table not found: global_test
```

global_test is gone again. not ideal

This is what the commit log screen on workbench looks like:

Image

Best regards,
DuToit

### PR DESCRIPTION
**Pull request by elianddb**
Fix #10462
- Fix `dolt_ignore` and `dolt_nonlocal_tables` not being excluded from `dolt clean` default command and SQL interface.
- Add `dolt clean` `-x` flag to override `dolt_ignore` deletions; similar to `git clean -x`.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.56         | 0.55       | -1.79          |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.82         | 1.86       | 2.2            |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 22.28        | 21.89      | -1.75          |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.37         | 5.28       | -1.68          |
| select_random_points | 0.54         | 0.54       | 0.0            |
| select_random_ranges | 0.55         | 0.57       | 3.64           |
| table_scan           | 22.28        | 22.28      | 0.0            |
| types_table_scan     | 66.84        | 65.65      | -1.78          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.79       | -1.74          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.56         | 0.55       | -1.79          |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.82         | 1.82       | 0.0            |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.54         | 0.54       | 0.0            |
| select_random_ranges | 0.55         | 0.56       | 1.82           |
| table_scan           | 21.89        | 22.28      | 1.78           |
| types_table_scan     | 66.84        | 65.65      | -1.78          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.02         | 3.07       | 1.66           |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.25         | 3.19       | -1.85          |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.79         | 6.79       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.56         | 0.54       | -3.57          |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.86         | 1.82       | -2.15          |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 21.89        | 22.28      | 1.78           |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.37         | 5.37       | 0.0            |
| select_random_points | 0.54         | 0.54       | 0.0            |
| select_random_ranges | 0.55         | 0.56       | 1.82           |
| table_scan           | 21.89        | 22.28      | 1.78           |
| types_table_scan     | 65.65        | 66.84      | 1.81           |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.79       | -1.74          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 62.19          | 1.82           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 069285c086ce9e9c40683941185077ffc5121efa | 37.47    | dolt           | 1c4d96e30f088e941a3d2c1db48d2a635cb0f2d1 | 36.99  | -1.28          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4748ed5</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4748ed5</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 62.19          | 1.82           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 069285c086ce9e9c40683941185077ffc5121efa | 37.96    | dolt           | 73ec42057f069b6e65dea747b3af723399e18dbf | 37.67  | -0.76          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 069285c086ce9e9c40683941185077ffc5121efa | 38.03    | dolt           | 4748ed5eab99f7d0c4f813b301c21580f4acecbf | 38.25  | 0.58           |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.57         | 0.58       | 1.75           |
| groupby_scan         | 9.73         | 9.91       | 1.85           |
| index_join           | 1.82         | 1.82       | 0.0            |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.28         | 0.27       | -3.57          |
| oltp_read_only       | 5.28         | 5.37       | 1.7            |
| select_random_points | 0.54         | 0.53       | -1.85          |
| select_random_ranges | 0.55         | 0.56       | 1.82           |
| table_scan           | 22.28        | 21.89      | -1.75          |
| types_table_scan     | 66.84        | 66.84      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.79         | 6.79       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>e23ae11</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>e23ae11</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 62.19            | 61.08          | -1.78          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 621a8103614c35a377646068055be27b079d6e60 | 37.71    | dolt           | e23ae11e59596f0be19f7688b855a27e397767e8 | 37.67  | -0.11          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.57         | 0.57       | 0.0            |
| groupby_scan         | 10.65        | 10.84      | 1.78           |
| index_join           | 1.89         | 1.89       | 0.0            |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.27         | 0.28       | 3.7            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.54         | 0.54       | 0.0            |
| select_random_ranges | 0.55         | 0.55       | 0.0            |
| table_scan           | 21.89        | 22.28      | 1.78           |
| types_table_scan     | 66.84        | 66.84      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.79         | 6.79       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>0175a2d</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>0175a2d</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 7e1229703820cf87453957418c6e970d134df1c4 | 37.98    | dolt           | 0175a2d098a55acf29afc82ad07697851719a86c | 37.3   | -1.79          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.57         | 0.57       | 0.0            |
| groupby_scan         | 9.73         | 9.91       | 1.85           |
| index_join           | 1.82         | 1.82       | 0.0            |
| index_join_scan      | 1.32         | 1.34       | 1.52           |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.27         | 0.28       | 3.7            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.53         | 0.54       | 1.89           |
| select_random_ranges | 0.55         | 0.55       | 0.0            |
| table_scan           | 22.28        | 21.89      | -1.75          |
| types_table_scan     | 66.84        | 66.84      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.79         | 6.79       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>da41e3e</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>da41e3e</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 7e1229703820cf87453957418c6e970d134df1c4 | 38.13    | dolt           | da41e3e1933f9c0c7426343f50121d1a1af1dfb7 | 37.63  | -1.31          |

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_nonlocal.go [hunk 1]
```diff
@@ -209,4 +209,34 @@ var NonlocalScripts = []queries.ScriptTest{
...
+		},
+		Assertions: []queries.ScriptTestAssertion{
+			{
+				Query:    "SELECT * FROM global_test;",
+				Expected: []sql.Row{{1, "one"}},
+			},
+			{
+				Query:    "CALL dolt_clean();",
+				Expected: []sql.Row{{0}},
+			},
```
Comment (fulghum) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_nonlocal.go:231]: Probably good to also test with explicitly using `call dolt-clean('-x');` just to assert that `-x` won't affect nonlocal tables, like the docs call out.

File: go/cmd/dolt/cli/flags.go [hunk 2]
```diff
@@ -17,77 +17,78 @@ package cli
...
+	SquashParam            = "squash"
+	StagedFlag             = "staged"
+	StatFlag               = "stat"
+	SystemFlag             = "system"
+	TablesFlag             = "tables"
+	TheirsFlag             = "theirs"
+	TrackFlag              = "track"
+	UpperCaseAllFlag       = "ALL"
+	UserFlag               = "user"
+	ExcludeIgnoreRulesFlag = "x"
```
Comment (angelamayxie) [inline go/cmd/dolt/cli/flags.go]: these seem to be in alphabetical order. move new constant to after `EmptyParam`

File: go/cmd/dolt/commands/clean.go [hunk 3]
```diff
@@ -32,16 +32,17 @@ const (
 
 var cleanDocContent = cli.CommandDocumentationContent{
 	ShortDesc: "Deletes untracked working tables",
-	LongDesc: "{{.EmphasisLeft}}dolt clean [--dry-run]{{.EmphasisRight}}\n\n" +
+	LongDesc: "{{.EmphasisLeft}}dolt clean [--dry-run] [-x]{{.EmphasisRight}}\n\n" +
```
Comment (angelamayxie) [inline go/cmd/dolt/commands/clean.go:35]: is there a UX reason for using `-x`? Like are we mirroring Git in any way? If not, it seems kinda random and we should probably use a more descriptive flag

Comment (elianddb) [reply go/cmd/dolt/commands/clean.go:35]: [Git](https://git-scm.com/docs/git-clean) does use `-x` only which is weird. I was looking to see if they had a more descriptive name.

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_nonlocal.go [hunk 4]
```diff
@@ -209,4 +209,34 @@ var NonlocalScripts = []queries.ScriptTest{
 			},
 		},
 	},
+	// https://github.com/dolthub/dolt/issues/10462
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_nonlocal.go]: put this comment inside the brackets (right above Name)

File: go/cmd/dolt/commands/clean.go (hunk 3 above)
Comment (angelamayxie) [reply go/cmd/dolt/commands/clean.go:35]: Okay, that's fine then :)

**Review by fulghum — APPROVED** [review]
Looks good! Just one small request for the nonlocal table test.

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_clean.go [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+
+package enginetest
+
+import (
+	"github.com/dolthub/go-mysql-server/enginetest/queries"
+	"github.com/dolthub/go-mysql-server/sql"
+)
+
+func init() {
+	DoltProcedureTests = append(DoltProcedureTests, DoltCleanProcedureScripts...)
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_clean.go]: this is hacky. remove the init, and either append DoltCleanProcedureScripts when DoltProcedureTests is called to be tested or have a separate test that tests DoltCleanProcedureScripts

**Review by angelamayxie — APPROVED** [review]

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.57         | 0.56       | -1.75          |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.82         | 1.82       | 0.0            |
| index_join_scan      | 1.34         | 1.34       | 0.0            |
| index_scan           | 21.89        | 21.89      | 0.0            |
| oltp_point_select    | 0.27         | 0.28       | 3.7            |
| oltp_read_only       | 5.37         | 5.28       | -1.68          |
| select_random_points | 0.53         | 0.54       | 1.89           |
| select_random_ranges | 0.56         | 0.57       | 1.79           |
| table_scan           | 21.89        | 21.89      | 0.0            |
| types_table_scan     | 65.65        | 65.65      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.07       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.79       | -1.74          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 <table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>f0e4dfd</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>f0e4dfd</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
 |      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 7c58d972cfa5711f173cbe95fd27de5fecea629f | 37.94    | dolt           | f0e4dfd7ff10bfe268e130fa033c269b9dda91dd | 37.75  | -0.5           |
