### PR TITLE
Fix auto increment state after backup restore

### LINKED ISSUE #10892: AUTO_INCREMENT value lost after dolt backup restore
Dolt version:

```
dolt version
Warning: Unknown global config option 'sqlserver.cluster.dolt_cluster_role'. Use `dolt config --global --unset sqlserver.cluster.dolt_cluster_role` to remove.
Warning: Unknown global config option 'sqlserver.cluster.dolt_cluster_role_epoch'. Use `dolt config --global --unset sqlserver.cluster.dolt_cluster_role_epoch` to remove.
dolt version 1.86.2
```

Use the following SQL to back up the `insight_metabase` database:

```sql
call dolt_add('-A');
call dolt_backup('add','local_backup', 'file:///db/dolt_backup/insight_metabase_20260417142401');
call dolt_backup('sync','local_backup');
call dolt_backup('remove', 'local_backup');
```

Use the following command to restore the database:

```
dolt backup restore file:///db/dolt_backup/insight_metabase_20260417142401 backup_metabase ;
```

The table creation statement for `insight_metabase` is as follows:

```sql
insight_metabase/main*> show create table report_card;
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                      |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| report_card | CREATE TABLE `report_card` (                                                                                                                      |
|             |   `id` int NOT NULL AUTO_INCREMENT,                                                                                                               |
|             |   `created_at` timestamp(6) NOT NULL,                                                                                                             |
|             |   `updated_at` timestamp(6),                                                                                                                      |
|             |   `name` varchar(254) NOT NULL,                                                                                                                   |
|             |   `description` longtext,                                                                                                                         |
|             |   `display` varchar(254) NOT NULL,                                                                                                                |
|             |   `dataset_query` longtext,                                                                                                                       |
|             |   `visualization_settings` longtext,                                                                                                              |
|             |   `creator_id` int NOT NULL,                                                                                                                      |
|             |   `database_id` int NOT NULL,                                                                                                                     |
|             |   `table_id` int DEFAULT NULL,                                                                                                                    |
|             |   `query_type` varchar(16) DEFAULT NULL,                                                                                                          |
|             |   `archived` bit(1) NOT NULL DEFAULT b'0',                                                                                                        |
|             |   `collection_id` int DEFAULT NULL COMMENT 'Optional ID of Collection this Card belongs to.',                                                     |
|             |   `public_uuid` char(36) DEFAULT NULL COMMENT 'Unique UUID used to in publically-accessible links to this Card.',                                 |
|             |   `made_public_by_id` int DEFAULT NULL COMMENT 'The ID of the User who first publically shared this Card.',                                       |
|             |   `enable_embedding` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Is this Card allowed to be embedded in different websites (using a signed JWT)?',      |
|             |   `embedding_params` longtext,                                                                                                                    |
|             |   `cache_ttl` int DEFAULT NULL COMMENT 'The maximum time, in seconds, to return cached results for this Card rather than running a new query.',   |
|             |   `result_metadata` longtext,                                                                                                                     |
|             |   `collection_position` smallint DEFAULT NULL COMMENT 'Optional pinned position for this item in its Collection. NULL means item is not pinned.', |
|             |   `entity_id` char(21) DEFAULT NULL COMMENT 'Random NanoID tag for unique identity.',                                                             |
|             |   `parameters` longtext COMMENT 'List of parameter associated to a card',                                                                         |
|             |   `parameter_mappings` longtext COMMENT 'List of parameter associated to a card',                                                                 |
|             |   `collection_preview` bit(1) NOT NULL DEFAULT b'1',                                                                                              |
|             |   `metabase_version` varchar(100) COMMENT 'Metabase version used to create the card.',                                                            |
|             |   `type` varchar(16) NOT NULL DEFAULT 'question' COMMENT 'The type of card, could be ''question'', ''model'', ''metric''',                        |
|             |   `initially_published_at` timestamp(6) COMMENT 'The timestamp when the card was first published in a static embed',                              |
|             |   `cache_invalidated_at` timestamp(6) COMMENT 'An invalidation time that can supersede cache_config.invalidated_at',                              |
|             |   `last_used_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),                                                                              |
|             |   `view_count` int NOT NULL DEFAULT '0' COMMENT 'Keeps a running count of card views',                                                            |
|             |   `archived_directly` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Was this thing trashed directly',                                                     |
|             |   `dataset_query_metrics_v2_migration_backup` longtext COMMENT 'The copy of dataset_query before the metrics v2 migration',                       |
|             |   `source_card_id` int COMMENT 'The ID of the model or question this card is based on',                                                           |
|             |   `dashboard_id` int COMMENT 'The dashboard that owns the card, if it is a dashboard-internal card.',                                             |
|             |   `card_schema` int NOT NULL DEFAULT '20' COMMENT 'Arbitrary revision number for how we store queries in report_card',                            |
|             |   PRIMARY KEY (`id`),                                                                                                                             |
|             |   UNIQUE KEY `entity_id` (`entity_id`),                                                                                                           |
|             |   KEY `fk_card_made_public_by_id` (`made_public_by_id`),                                                                                          |
|             |   KEY `fk_report_card_ref_database_id` (`database_id`),                                                                                           |
|             |   KEY `fk_report_card_ref_table_id` (`table_id`),                                                                                                 |
|             |   KEY `idx_card_collection_id` (`collection_id`),                                                                                                 |
|             |   KEY `idx_card_creator_id` (`creator_id`),                                                                                                       |
|             |   KEY `idx_card_public_uuid` (`public_uuid`),                                                                                                     |
|             |   KEY `idx_report_card_card_schema` (`card_schema`),                                                                                              |
|             |   KEY `idx_report_card_dashboard_id` (`dashboard_id`),                                                                                            |
|             |   KEY `idx_report_card_source_card_id` (`source_card_id`),                                                                                        |
|             |   UNIQUE KEY `public_uuid` (`public_uuid`),                                                                                                       |
|             |   CONSTRAINT `fk_card_collection_id` FOREIGN KEY (`collection_id`) REFERENCES `collection` (`id`) ON DELETE SET NULL,                             |
|             |   CONSTRAINT `fk_card_made_public_by_id` FOREIGN KEY (`made_public_by_id`) REFERENCES `core_user` (`id`) ON DELETE CASCADE,                       |
|             |   CONSTRAINT `fk_card_ref_user_id` FOREIGN KEY (`creator_id`) REFERENCES `core_user` (`id`) ON DELETE CASCADE,                                    |
|             |   CONSTRAINT `fk_report_card_ref_dashboard_id` FOREIGN KEY (`dashboard_id`) REFERENCES `report_dashboard` (`id`) ON DELETE CASCADE,               |
|             |   CONSTRAINT `fk_report_card_ref_database_id` FOREIGN KEY (`database_id`) REFERENCES `metabase_database` (`id`) ON DELETE CASCADE,                |
|             |   CONSTRAINT `fk_report_card_ref_table_id` FOREIGN KEY (`table_id`) REFERENCES `metabase_table` (`id`) ON DELETE CASCADE,                         |
|             |   CONSTRAINT `fk_report_card_source_card_id_ref_report_card_id` FOREIGN KEY (`source_card_id`) REFERENCES `report_card` (`id`) ON DELETE CASCADE  |
|             | ) ENGINE=InnoDB AUTO_INCREMENT=449 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci                                                             |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

The table creation statement for `backup_metabase` is as follows:

```sql
backup_metabase/main*> show create table report_card;
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                      |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| report_card | CREATE TABLE `report_card` (                                                                                                                      |
|             |   `id` int NOT NULL AUTO_INCREMENT,                                                                                                               |
|             |   `created_at` timestamp(6) NOT NULL,                                                                                                             |
|             |   `updated_at` timestamp(6),                                                                                                                      |
|             |   `name` varchar(254) NOT NULL,                                                                                                                   |
|             |   `description` longtext,                                                                                                                         |
|             |   `display` varchar(254) NOT NULL,                                                                                                                |
|             |   `dataset_query` longtext,                                                                                                                       |
|             |   `visualization_settings` longtext,                                                                                                              |
|             |   `creator_id` int NOT NULL,                                                                                                                      |
|             |   `database_id` int NOT NULL,                                                                                                                     |
|             |   `table_id` int DEFAULT NULL,                                                                                                                    |
|             |   `query_type` varchar(16) DEFAULT NULL,                                                                                                          |
|             |   `archived` bit(1) NOT NULL DEFAULT b'0',                                                                                                        |
|             |   `collection_id` int DEFAULT NULL COMMENT 'Optional ID of Collection this Card belongs to.',                                                     |
|             |   `public_uuid` char(36) DEFAULT NULL COMMENT 'Unique UUID used to in publically-accessible links to this Card.',                                 |
|             |   `made_public_by_id` int DEFAULT NULL COMMENT 'The ID of the User who first publically shared this Card.',                                       |
|             |   `enable_embedding` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Is this Card allowed to be embedded in different websites (using a signed JWT)?',      |
|             |   `embedding_params` longtext,                                                                                                                    |
|             |   `cache_ttl` int DEFAULT NULL COMMENT 'The maximum time, in seconds, to return cached results for this Card rather than running a new query.',   |
|             |   `result_metadata` longtext,                                                                                                                     |
|             |   `collection_position` smallint DEFAULT NULL COMMENT 'Optional pinned position for this item in its Collection. NULL means item is not pinned.', |
|             |   `entity_id` char(21) DEFAULT NULL COMMENT 'Random NanoID tag for unique identity.',                                                             |
|             |   `parameters` longtext COMMENT 'List of parameter associated to a card',                                                                         |
|             |   `parameter_mappings` longtext COMMENT 'List of parameter associated to a card',                                                                 |
|             |   `collection_preview` bit(1) NOT NULL DEFAULT b'1',                                                                                              |
|             |   `metabase_version` varchar(100) COMMENT 'Metabase version used to create the card.',                                                            |
|             |   `type` varchar(16) NOT NULL DEFAULT 'question' COMMENT 'The type of card, could be ''question'', ''model'', ''metric''',                        |
|             |   `initially_published_at` timestamp(6) COMMENT 'The timestamp when the card was first published in a static embed',                              |
|             |   `cache_invalidated_at` timestamp(6) COMMENT 'An invalidation time that can supersede cache_config.invalidated_at',                              |
|             |   `last_used_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),                                                                              |
|             |   `view_count` int NOT NULL DEFAULT '0' COMMENT 'Keeps a running count of card views',                                                            |
|             |   `archived_directly` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Was this thing trashed directly',                                                     |
|             |   `dataset_query_metrics_v2_migration_backup` longtext COMMENT 'The copy of dataset_query before the metrics v2 migration',                       |
|             |   `source_card_id` int COMMENT 'The ID of the model or question this card is based on',                                                           |
|             |   `dashboard_id` int COMMENT 'The dashboard that owns the card, if it is a dashboard-internal card.',                                             |
|             |   `card_schema` int NOT NULL DEFAULT '20' COMMENT 'Arbitrary revision number for how we store queries in report_card',                            |
|             |   PRIMARY KEY (`id`),                                                                                                                             |
|             |   UNIQUE KEY `entity_id` (`entity_id`),                                                                                                           |
|             |   KEY `fk_card_made_public_by_id` (`made_public_by_id`),                                                                                          |
|             |   KEY `fk_report_card_ref_database_id` (`database_id`),                                                                                           |
|             |   KEY `fk_report_card_ref_table_id` (`table_id`),                                                                                                 |
|             |   KEY `idx_card_collection_id` (`collection_id`),                                                                                                 |
|             |   KEY `idx_card_creator_id` (`creator_id`),                                                                                                       |
|             |   KEY `idx_card_public_uuid` (`public_uuid`),                                                                                                     |
|             |   KEY `idx_report_card_card_schema` (`card_schema`),                                                                                              |
|             |   KEY `idx_report_card_dashboard_id` (`dashboard_id`),                                                                                            |
|             |   KEY `idx_report_card_source_card_id` (`source_card_id`),                                                                                        |
|             |   UNIQUE KEY `public_uuid` (`public_uuid`),                                                                                                       |
|             |   CONSTRAINT `fk_card_collection_id` FOREIGN KEY (`collection_id`) REFERENCES `collection` (`id`) ON DELETE SET NULL,                             |
|             |   CONSTRAINT `fk_card_made_public_by_id` FOREIGN KEY (`made_public_by_id`) REFERENCES `core_user` (`id`) ON DELETE CASCADE,                       |
|             |   CONSTRAINT `fk_card_ref_user_id` FOREIGN KEY (`creator_id`) REFERENCES `core_user` (`id`) ON DELETE CASCADE,                                    |
|             |   CONSTRAINT `fk_report_card_ref_dashboard_id` FOREIGN KEY (`dashboard_id`) REFERENCES `report_dashboard` (`id`) ON DELETE CASCADE,               |
|             |   CONSTRAINT `fk_report_card_ref_database_id` FOREIGN KEY (`database_id`) REFERENCES `metabase_database` (`id`) ON DELETE CASCADE,                |
|             |   CONSTRAINT `fk_report_card_ref_table_id` FOREIGN KEY (`table_id`) REFERENCES `metabase_table` (`id`) ON DELETE CASCADE,                         |
|             |   CONSTRAINT `fk_report_card_source_card_id_ref_report_card_id` FOREIGN KEY (`source_card_id`) REFERENCES `report_card` (`id`) ON DELETE CASCADE  |
|             | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci                                                                                |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Why does the table structure restored from the backup lose `AUTO_INCREMENT=449`?

When I want to insert a new record into the database backup_metabase, the auto-increment ID will start from 1, causing a primary key conflict error.

---
I have discovered a new situation: when the restore is completed and no application is connected to the database, the `AUTO_INCREMENT` value exists and is consistent with the original database. However, after Metabase starts using the restored database, the `AUTO_INCREMENT` value is lost.

### PR DESCRIPTION
**Pull request by elianddb**
Fix database restored with `dolt backup restore` could generate incorrect `AUTO_INCREMENT` values when accessed through a still-running `dolt sql-server`.

The restored table persisted the correct auto-increment value, but the server’s in-memory auto-increment tracker could be missing state for the restored database. The tracker now initializes missing table state from the restored table before allocating ids.
Fix dolthub/dolt#10892

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.55         | 0.55       | 0.0            |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.86         | 1.86       | 0.0            |
| index_join_scan      | 1.37         | 1.37       | 0.0            |
| index_scan           | 22.69        | 22.28      | -1.81          |
| oltp_point_select    | 0.26         | 0.26       | 0.0            |
| oltp_read_only       | 5.09         | 5.09       | 0.0            |
| select_random_points | 0.51         | 0.51       | 0.0            |
| select_random_ranges | 0.56         | 0.57       | 1.79           |
| table_scan           | 22.69        | 22.28      | -1.81          |
| types_table_scan     | 68.05        | 66.84      | -1.78          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.13       | 1.95           |
| oltp_read_write       | 11.04        | 11.04      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.02         | 3.02       | 0.0            |
| oltp_write_only       | 5.99         | 5.99       | 0.0            |
| types_delete_insert   | 6.91         | 6.91       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4f6b426</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4f6b426</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 55.82            | 54.83          | -1.77          |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | b2acc3421e6251d442cf74f97335ec6c4863d05a | 43.56    | dolt           | 7e12ddf2a656e01fb36f4dc8d1d83a84a80ff23e | 44.04  | 1.1            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4d35e02</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4d35e02</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by angelamayxie — APPROVED** [review]

File: go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go [hunk 1]
```diff
@@ -99,31 +99,78 @@ func getGCSafepointController(ctx context.Context) *gcctx.GCSafepointController
 	return gcctx.GetGCSafepointController(ctx)
 }
 
-func loadAutoIncValue(sequences *sync.Map, tableName string) uint64 {
+func loadAutoIncValue(sequences *sync.Map, tableName string) (uint64, bool) {
```
Comment (nicktobey) [inline go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go]: We should name the return values here so it's clear what the boolean value represents.

File: go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go [hunk 2]
```diff
@@ -137,12 +184,31 @@ func (a *AutoIncrementTracker) Next(ctx *sql.Context, tbl string, insertVal inte
...
 	if a.lockMode == LockMode_Interleaved {
 		release := a.mm.Lock(tbl)
 		defer release()
+		locked = true
 	}
 
-	curr := loadAutoIncValue(a.sequences, tbl)
+	curr, ok := loadAutoIncValue(a.sequences, tbl)
+	if !ok {
+		if !locked {
```
Comment (nicktobey) [inline go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go:196]: This definitely needs comments to explain what's going on.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7e12ddf</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7e12ddf</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by nicktobey — APPROVED** [review]
