### PR TITLE
Fix `UPDATE` when table has a `BINARY` primary key and a foreign key to use `bytes.Equal`

### LINKED ISSUE #10903: `UPDATE` panics with a binary primary key and some foreign key since 1.86.0
It seems there has been a bug introduced somewhere around Dolt 1.86.0, where I can't update tables that have binary primary keys and some constraint to a different table. The type of the constrainted index doesn't seem to matter it's the primary key of the updated table that's causing the issue.

To reproduce:
[repro.sql](https://github.com/user-attachments/files/26856267/repro.sql)
```sh
$ dolt sql < repro.sql
```
My output: 
[panic.log](https://github.com/user-attachments/files/26856301/panic.log)

I tried this on Dolt 1.85.0 and it ran fine, so that's hopefully narrowing down the issue.

### PR DESCRIPTION
**Pull request by elianddb**
Updating a row in a table with a `BINARY` or `VARBINARY` primarkey key and a foreign key caused a runtime panic. Any secondary index on such a table (including the index backing a foreign key constraint) would trigger it.
- Fix `isNoopUpdate` to use `bytes.Equal` when comparing `BINARY`/`VARBINARY` column values

Fix dolthub/dolt#10903

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.55         | 0.55       | 0.0            |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.86         | 1.86       | 0.0            |
| index_join_scan      | 1.37         | 1.37       | 0.0            |
| index_scan           | 22.28        | 22.28      | 0.0            |
| oltp_point_select    | 0.26         | 0.26       | 0.0            |
| oltp_read_only       | 5.09         | 5.09       | 0.0            |
| select_random_points | 0.51         | 0.51       | 0.0            |
| select_random_ranges | 0.56         | 0.56       | 0.0            |
| table_scan           | 22.28        | 22.28      | 0.0            |
| types_table_scan     | 66.84        | 66.84      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.32         | 6.32       | 0.0            |
| oltp_insert           | 3.07         | 3.13       | 1.95           |
| oltp_read_write       | 11.24        | 11.24      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.07         | 3.02       | -1.63          |
| oltp_write_only       | 5.99         | 5.99       | 0.0            |
| types_delete_insert   | 6.79         | 6.91       | 1.77           |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9db069c</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9db069c</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 55.82            | 56.84          | 1.83           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | bb6bdd65b3c4fe02c1764e5b92f503f44b2c7223 | 43.56    | dolt           | 66b82d43922317341787c93e3a580ee04ff96868 | 42.44  | -2.57          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>17476b9</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>17476b9</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_foreign_keys.go [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+import (
+	"github.com/dolthub/go-mysql-server/enginetest/queries"
+	"github.com/dolthub/go-mysql-server/sql"
+	"github.com/dolthub/go-mysql-server/sql/plan"
+	"github.com/dolthub/go-mysql-server/sql/types"
+)
+
+// DoltForeignKeyTests are Dolt-specific tests for foreign key behavior, separate from the
+// engine-level foreign key tests in go-mysql-server.
+var DoltForeignKeyTests = []queries.ScriptTest{
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_foreign_keys.go:26]: I'm fine with this being its own set of script tests, but there are probably some other foreign key tests in our other script tests. can you file an issue to clean up our tests and make sure they're organized properly?

File: go/libraries/doltcore/sqle/enginetest/dolt_queries_foreign_keys.go [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+	{
+		// See https://github.com/dolthub/dolt/issues/10903
+		Name: "UPDATE on table with BINARY primary key, explicit secondary index, and foreign key does not panic",
```
Comment (angelamayxie) [inline go/libraries/doltcore/sqle/enginetest/dolt_queries_foreign_keys.go]: I think you should remove the `foreign key does not panic` part of each of these test names. Tests should describe desired behavior, not undesired behavior (not panicking, not erroring out, etc, should be a given)

File: go/go.mod [hunk 3]
```diff
@@ -209,3 +209,4 @@ require (
 )
 
 go 1.25.6
+
```
Comment (angelamayxie) [inline go/go.mod]: extra line is probably unnecessary and would probably get removed with `go mod tidy` or autoformatting in goland. better to remove it in the PR

**Review by angelamayxie — APPROVED** [review]

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>66b82d4</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>66b82d4</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
