### PR TITLE
Fix `diff` and `show` hiding committed tables matching `dolt_ignore`

### LINKED ISSUE #10782: dolt show / dolt diff retroactively hides committed tables added to dolt_ignore
## Summary

`dolt show` and `dolt diff` silently suppress output for tables that were committed **before** being added to `dolt_ignore`. This retroactively alters the view of historical commits. `--summary` correctly shows the table, proving the data is in the commit but the default renderer skips it.

## Expected behavior

`dolt_ignore` should only affect staging of new tables (as documented). Viewing historical commits via `dolt show` or `dolt diff` should always show the full committed content, regardless of the current `dolt_ignore` state.

## Actual behavior

After adding a previously committed table to `dolt_ignore`:
- `dolt show <commit>` no longer displays the table's diff (it did before the ignore was added)
- `dolt diff <parent> <commit>` also hides the table
- `dolt show --summary <commit>` **still shows** the table as `added` with `schema_change=true`

This means `dolt_ignore` retroactively filters the rendering of committed history.

## Reproduction

```bash
#!/usr/bin/env bash
set -euo pipefail

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT
cd "$WORKDIR"

# Setup
dolt init
dolt sql -q "CREATE TABLE existing (id INT PRIMARY KEY, val TEXT);"
dolt sql -q "INSERT INTO existing VALUES (1, 'hello');"
dolt add .
dolt commit -m "initial commit"

# Step 1: Create and commit the_table
dolt sql -q "CREATE TABLE the_table (pk INT PRIMARY KEY, name TEXT);"
dolt sql -q "INSERT INTO existing VALUES (2, 'world');"
dolt add .
dolt commit -m "add the_table and insert into existing"

COMMIT=$(dolt log -n 1 --oneline | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $1}')

echo "=== BEFORE ignore: dolt show shows the_table ==="
dolt show "$COMMIT"

echo ""
echo "=== BEFORE ignore: dolt show --summary ==="
dolt show --summary "$COMMIT"

# Step 2: Add the_table to dolt_ignore
dolt sql -q "INSERT INTO dolt_ignore VALUES ('the_table', true);"
dolt add dolt_ignore
dolt commit -m "ignore the_table"

echo ""
echo "=== AFTER ignore: dolt show hides the_table ==="
dolt show "$COMMIT"

echo ""
echo "=== AFTER ignore: dolt show --summary still shows it ==="
dolt show --summary "$COMMIT"
```

## Output

**Before adding to `dolt_ignore`**, `dolt show` displays both tables:
```
diff --dolt a/existing b/existing
...
diff --dolt a/the_table b/the_table
added table
+CREATE TABLE `the_table` (...)
```

**After adding to `dolt_ignore`**, `dolt show` on the **same commit** hides `the_table`:
```
diff --dolt a/existing b/existing
...
(the_table is gone)
```

But `--summary` still shows it:
```
| existing   | modified  | true        | false         |
| the_table  | added     | false       | true          |
```

`dolt diff` behaves identically — `the_table` vanishes from default output but remains in `--summary`.

## Documentation reference

The [dolt_ignore docs](https://docs.dolthub.com/sql-reference/version-control/dolt-system-tables#dolt_ignore) state:

> This only affects the staging of new tables.

And:

> `dolt diff` won't display ignored tables, and `dolt show` won't display ignored tables unless the additional `--ignored` flag is passed.

The second sentence appears to explain the current behavior, but in context it reads as applying to untracked/working-set tables — not to committed history. At minimum, the docs should clarify that `dolt_ignore` retroactively filters `dolt show` and `dolt diff` on historical commits.

However, I'd argue this is a bug rather than a documentation gap: historical commits should render consistently regardless of the current working-set ignore configuration.

## Environment

- dolt version: 1.84.0
- OS: Linux (Ubuntu)

### PR DESCRIPTION
**Pull request by elianddb**
Ignore patterns apply to staging untracked tables, not committed history. `dolt diff`, `dolt show`, and `dolt_diff_summary()` were incorrectly filtering tables from commit-to-commit diffs when those tables matched a `dolt_ignore` pattern after the commit.
- Add `IsWorkingSetRef` to `doltdb` and `ShouldIgnoreDelta` to `IgnorePatterns` as shared helpers.
- Fix `diffUserTables` to skip ignore pattern evaluation when both refs are commits, using `hasWorkingSet` on `diffDatasets`
- Fix `dolt_diff_summary()` to apply the same gate, correcting commit-to-commit queries.
- Restrict ignore filtering to newly added or dropped tables in both layers; modifications to tracked tables are always shown.
- Add enginetests for `dolt_diff()`, `dolt_patch()` and `dolt_diff_summary()` to lock in correct commit-to-commit behavior across independent implementations.

Fix dolthub/dolt#10782
Related dolthub/docs#2813

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.55         | 0.55       | 0.0            |
| groupby_scan         | 9.91         | 9.91       | 0.0            |
| index_join           | 1.82         | 1.89       | 3.85           |
| index_join_scan      | 1.34         | 1.37       | 2.24           |
| index_scan           | 23.1         | 22.28      | -3.55          |
| oltp_point_select    | 0.28         | 0.27       | -3.57          |
| oltp_read_only       | 5.37         | 5.37       | 0.0            |
| select_random_points | 0.54         | 0.54       | 0.0            |
| select_random_ranges | 0.56         | 0.56       | 0.0            |
| table_scan           | 22.69        | 22.28      | -1.81          |
| types_table_scan     | 66.84        | 66.84      | 0.0            |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.43         | 6.32       | -1.71          |
| oltp_insert           | 3.13         | 3.13       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.25         | 3.25       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.91       | 0.0            |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>9f922ee</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>9f922ee</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 58.92            | 59.99          | 1.82           |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 7054d6ee44c2756e850ec9bfd6417d0c9c32251d | 42.48    | dolt           | 7f9bf383779e431aa3e1aeb464ad3657d95b5a65 | 41.13  | -3.18          |

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>cf90324</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>cf90324</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3f8440e</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3f8440e</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>cb2dfad</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>cb2dfad</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>4428bbe</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>4428bbe</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Review by jycor — APPROVED** [review]
LGTM

File: go/cmd/dolt/commands/diff.go [hunk 1]
```diff
@@ -922,25 +932,12 @@ func diffUserTables(queryist cli.Queryist, sqlCtx *sql.Context, dArgs *diffArgs)
...
-		// Don't print tables if one side of the diff is an ignored table in the working set being added.
-		if len(delta.FromTableName.Name) == 0 {
-			ignoreResult, err := ignoredTablePatterns.IsTableNameIgnored(delta.ToTableName)
-			if err != nil {
-				return errhand.VerboseErrorFromError(err)
-			}
-			if ignoreResult == doltdb.Ignore {
-				continue
-			}
+		ignore, err := ignoredTablePatterns.ShouldIgnoreDelta(delta.IsAdd(), delta.IsDrop(), delta.ToTableName, delta.FromTableName)
```
Comment (jycor) [inline go/cmd/dolt/commands/diff.go:935]: `ignoredTablePatterns` might be nil here; not sure if you need to initialize with default pattern map.

Comment (elianddb) [reply go/cmd/dolt/commands/diff.go:935]: `IgnorePatterns` is `type IgnorePatterns []IgnorePattern`, and we declare a nil slice value so the `ip` ptr should be non-nil. Also, `range *ip` on a nil slice is safe, producing zero iters.

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>cc5804e</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>cc5804e</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>3b9df5b</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>3b9df5b</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>cefa66a</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>cefa66a</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>5f2ded5</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>5f2ded5</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

File: go/libraries/doltcore/doltdb/doltdb.go [hunk 2]
```diff
@@ -48,7 +48,14 @@ const (
 	// we expect to resolve a commit spec, but need working or staged
 	Working = "WORKING"
 	Staged  = "STAGED"
+)
+
+// IsWorkingSetRef reports whether |ref| identifies the working set or staging area rather than a commit.
+func IsWorkingSetRef(ref string) bool {
+	return ref == Working || ref == Staged
+}
```
Comment (fulghum) [inline go/libraries/doltcore/doltdb/doltdb.go]: (minor) This feels a little out of place up mixed in with the var and const definitions. Probably better to move this down into the functions section with any other small public/exported functions.

**Review by fulghum — APPROVED** [review]
Looks good! Just one minor suggestion.

**Comment by coffeegoddd** [comment]
@coffeegoddd __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>7f9bf38</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>7f9bf38</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@elianddb __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>124ddc7</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>124ddc7</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>
