### PR TITLE
go: doltcore/sqle: database_provider.go: Fix a deadlock in DROP DATABASE.

### LINKED ISSUE #10692: Server permanently unresponsive after client crash during CREATE/DROP DATABASE
# Server permanently unresponsive after client crash during CREATE/DROP DATABASE

## Summary

If a client process crashes (SIGKILL, OOM, `os.Exit`, power loss) while a `CREATE DATABASE` or `DROP DATABASE` operation is in flight, the Dolt SQL server becomes **permanently unresponsive** to all queries. The server continues to accept TCP connections and responds to `COM_PING`, but every SQL statement — including `SELECT 1` — hangs indefinitely. The server must be restarted to recover.

NOTE - FULL DISCLOSURE: - **Reproducer developed with AI assistance** (GitHub Copilot)

## Version

Tested on `dolthub/dolt-sql-server:1.83.6` (Docker image).

## How to reproduce

A self-contained Go reproducer is attached below. It requires only a running Dolt SQL server:
[dolt-deadlock-repro-v2.tar.gz](https://github.com/user-attachments/files/26037812/dolt-deadlock-repro-v2.tar.gz)

```bash
# Start a fresh Dolt server with remote root access
docker run -d --name dolt-repro -p 3307:3306 \
  -e DOLT_ROOT_PASSWORD=test \
  dolthub/dolt-sql-server:1.83.6

# Wait for server to be ready, then grant remote access
sleep 3
docker exec dolt-repro dolt --host 127.0.0.1 --port 3306 \
  --no-tls -u root --password=test sql -q \
  "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'test';
   GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;"

# Build and run the reproducer (see main.go below)
cd dolt-deadlock-repro

# 1. Verify server is healthy
go run . --dsn 'root:test@tcp(localhost:3307)/' --mode=check
# Expected: Ping OK, SELECT 1 OK

# 2. Crash during DDL
go run . --dsn 'root:test@tcp(localhost:3307)/'
# Process exits with status 1

# 3. Verify server is now frozen
go run . --dsn 'root:test@tcp(localhost:3307)/' --mode=check
# Expected: Ping OK, SELECT 1 HANGS (context deadline exceeded)
```

The reproducer launches 10 goroutines doing `CREATE DATABASE` / `DROP DATABASE` in a tight loop, then calls `os.Exit(1)` after 150ms. Since `os.Exit` doesn't run defers or close connections, the OS RSTs all TCP connections — simulating a client crash. With 10 concurrent DDL workers, the server's global write lock is continuously held, making the crash reliably land mid-lock.

<details>
<summary><b>main.go</b> (click to expand)</summary>

```go
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	_ "github.com/go-sql-driver/mysql"
	"github.com/google/uuid"
)

func main() {
	dsn := flag.String("dsn", "root:test@tcp(localhost:3307)/", "MySQL DSN")
	mode := flag.String("mode", "kill", "'kill' to crash during DDL, 'check' to verify server state")
	flag.Parse()

	switch *mode {
	case "kill":
		runKill(*dsn)
	case "check":
		runCheck(*dsn)
	default:
		fmt.Fprintf(os.Stderr, "unknown mode: %s\n", *mode)
		os.Exit(1)
	}
}

func runKill(dsn string) {
	fmt.Println("=== Dolt deadlock reproducer ===")
	fmt.Println("Will crash (os.Exit) while CREATE/DROP DATABASE is in flight.")
	fmt.Println()

	// Verify server is healthy first
	if err := healthCheck(dsn); err != nil {
		fmt.Fprintf(os.Stderr, "server not healthy: %v\n", err)
		os.Exit(1)
	}

	db, err := sql.Open("mysql", dsn+"?timeout=30s&readTimeout=30s&writeTimeout=30s")
	if err != nil {
		fmt.Fprintf(os.Stderr, "sql.Open: %v\n", err)
		os.Exit(1)
	}
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(10)

	// Warm up the pool
	for i := 0; i < 10; i++ {
		go db.Ping()
	}
	time.Sleep(100 * time.Millisecond)

	// Launch DDL storm — 10 workers ensures the global write lock
	// (DoltDatabaseProvider.mu) is continuously held: when one writer
	// finishes, the next queued writer acquires it immediately.
	prefix := fmt.Sprintf("repro_%s", strings.ReplaceAll(uuid.New().String()[:8], "-", ""))
	fmt.Printf("Database prefix: %s\n", prefix)

	for i := 0; i < 10; i++ {
		go func(worker int) {
			counter := 0
			for {
				name := fmt.Sprintf("%s_w%d_%d", prefix, worker, counter)
				counter++
				log("[w%d] CREATE DATABASE %s", worker, name)
				if _, err := db.ExecContext(context.Background(), "CREATE DATABASE "+name); err != nil {
					log("[w%d] CREATE error: %v", worker, err)
					continue
				}
				log("[w%d] DROP DATABASE %s", worker, name)
				db.ExecContext(context.Background(), "DROP DATABASE "+name)
			}
		}(i)
	}

	// Crash after 150ms — gives workers time to queue on the mutex.
	// os.Exit does NOT run defers, does NOT close sql.DB,
	// does NOT close TCP connections.
	time.Sleep(150 * time.Millisecond)
	fmt.Println("\n*** CRASHING (os.Exit) — TCP connections will be RST'd ***")
	os.Exit(1)
}

func runCheck(dsn string) {
	fmt.Println("=== Post-crash server check ===")
	start := time.Now()

	db, err := sql.Open("mysql", dsn+"?timeout=3s&readTimeout=5s&writeTimeout=3s")
	if err != nil {
		fmt.Fprintf(os.Stderr, "sql.Open: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()
	db.SetMaxOpenConns(1)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	log("Ping...")
	if err := db.PingContext(ctx); err != nil {
		log("Ping FAILED: %v (+%s) — server unreachable", err, since(start))
		os.Exit(2)
	}
	log("Ping OK (+%s)", since(start))

	log("SELECT 1 (5s timeout)...")
	var result int
	if err := db.QueryRowContext(ctx, "SELECT 1").Scan(&result); err != nil {
		log("SELECT 1 FAILED: %v (+%s)", err, since(start))
		fmt.Println("\n*** SERVER IS FROZEN ***")
		fmt.Println("Ping works (no catalog lock needed), but all queries hang.")
		os.Exit(2)
	}
	log("SELECT 1 = %d (+%s) — server is healthy", result, since(start))
}

func healthCheck(dsn string) error {
	db, err := sql.Open("mysql", dsn+"?timeout=3s&readTimeout=5s&writeTimeout=3s")
	if err != nil {
		return err
	}
	defer db.Close()
	db.SetMaxOpenConns(1)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		return fmt.Errorf("ping: %w", err)
	}
	var n int
	if err := db.QueryRowContext(ctx, "SELECT 1").Scan(&n); err != nil {
		return fmt.Errorf("SELECT 1: %w", err)
	}
	fmt.Println("Pre-flight: server is healthy")
	return nil
}

func log(format string, args ...any) {
	fmt.Printf("[%s] %s\n", time.Now().Format("15:04:05.000"), fmt.Sprintf(format, args...))
}

func since(t time.Time) string {
	return time.Since(t).Truncate(time.Millisecond).String()
}
```

</details>

<details>
<summary><b>go.mod</b></summary>

```
module dolt-deadlock-repro

go 1.23

require (
	github.com/go-sql-driver/mysql v1.9.2
	github.com/google/uuid v1.6.0
)

require filippo.io/edwards25519 v1.1.0 // indirect
```

</details>

## Observed behavior

After the crash:

| Operation | Result |
|---|---|
| TCP connect | ✅ Succeeds instantly |
| MySQL handshake | ✅ Server sends greeting |
| `COM_PING` | ✅ Responds normally |
| Any SQL query (`SELECT 1`, `SHOW DATABASES`, etc.) | ❌ Hangs forever |
| `dolt sql -q '...'` inside container | ❌ Also hangs |

The server never recovers. Only a restart fixes it.

## Expected behavior

The server should recover after a client connection is lost, even if the disconnect happens during DDL operations. Queries from other connections should not be permanently blocked.

## Scenario

```mermaid
sequenceDiagram
    participant Client as Client Process
    participant Dolt as Dolt SQL Server
    participant Lock as provider.mu (RWMutex)

    Note over Client,Dolt: Normal operation — server is healthy

    Client->>Dolt: CREATE DATABASE test_xyz
    Dolt->>Lock: mu.Lock() — write lock acquired
    Note over Dolt: Heavy I/O in progress:<br/>MkDirs, InitRepo, WorkingRoot...

    Client--xClient: PROCESS CRASH (SIGKILL / OOM / os.Exit)
    Note over Client: OS sends TCP RST on all connections

    Note over Dolt: Connection handler goroutine<br/>detects i/o error eventually...
    Note over Lock: Write lock is never released

    Note over Dolt,Lock: From this point, ALL queries block forever

    participant Client2 as New Client
    Client2->>Dolt: TCP connect
    Dolt-->>Client2: MySQL handshake OK
    Client2->>Dolt: COM_PING
    Dolt-->>Client2: OK (no lock needed)
    Client2->>Dolt: SELECT 1
    Dolt->>Lock: mu.RLock() — blocks forever
    Note over Client2,Lock: Query hangs indefinitely.<br/>Write lock will never be released.
```

## Analysis

We believe the issue is in `DoltDatabaseProvider` ([database_provider.go](https://github.com/dolthub/dolt/blob/v1.83.6/go/libraries/doltcore/sqle/database_provider.go)):

- The provider uses a global `sync.RWMutex` (`mu`, line 70) to protect the database catalog.
- `CreateCollatedDatabase` (line 650) and `DropDatabase` (line 962) acquire a **write lock** and hold it during filesystem I/O (directory creation, repo init, noms storage writes, cleanup).
- `SessionDatabase` (line 1530) acquires a **read lock** for every SQL statement to resolve the database name.
- When a client's TCP connection is RST'd while the handler goroutine holds the write lock, the lock appears to be orphaned — it is never released.
- All subsequent queries block on `mu.RLock()` forever.

`COM_PING` still works because it doesn't go through the query analyzer and never calls `SessionDatabase`.

Go's `sync.RWMutex` has no ownership tracking, no timeout, and no deadlock detection. A goroutine that exits (or gets stuck) while holding a lock will never release it.

## Demo gif

Image

## Environment

- **Dolt**: `dolthub/dolt-sql-server:1.83.6` (Docker)
- **Client**: Go 1.24, `go-sql-driver/mysql` v1.9.2
- **OS**: Linux (Docker containers on Linux host)

### PR DESCRIPTION
**Pull request by reltuk**
A lock-acquisition order error could cause DROP DATABASE to conflict on lock acquisition with a DoltSession's own Mutex. The result was that all sessions would then block indefinitely and irrecoverably on trying to access any database loaded in the server.

This changes the order of operations and the lock acquisition sequencing to not dead lock.

Note: finalization of DROP DATABASE with regards to sessions and ongoing queries which may be accessing the database is still somewhat lacking. To be improved in the future.

Fixes: #10692.

### CODE REVIEW

**Comment by coffeegoddd** [comment]
@reltuk __DOLT__
|      read_tests      | from_latency | to_latency | percent_change |
|----------------------|--------------|------------|----------------|
| covering_index_scan  | 0.55         | 0.55       | 0.0            |
| groupby_scan         | 10.09        | 9.91       | -1.78          |
| index_join           | 1.82         | 1.82       | 0.0            |
| index_join_scan      | 1.39         | 1.39       | 0.0            |
| index_scan           | 22.28        | 22.28      | 0.0            |
| oltp_point_select    | 0.27         | 0.27       | 0.0            |
| oltp_read_only       | 5.28         | 5.28       | 0.0            |
| select_random_points | 0.54         | 0.53       | -1.85          |
| select_random_ranges | 0.56         | 0.56       | 0.0            |
| table_scan           | 22.28        | 22.28      | 0.0            |
| types_table_scan     | 68.05        | 66.84      | -1.78          |


|      write_tests      | from_latency | to_latency | percent_change |
|-----------------------|--------------|------------|----------------|
| oltp_delete_insert    | 6.43         | 6.32       | -1.71          |
| oltp_insert           | 3.13         | 3.13       | 0.0            |
| oltp_read_write       | 11.45        | 11.45      | 0.0            |
| oltp_update_index     | 3.19         | 3.19       | 0.0            |
| oltp_update_non_index | 3.13         | 3.13       | 0.0            |
| oltp_write_only       | 6.09         | 6.09       | 0.0            |
| types_delete_insert   | 6.91         | 6.79       | -1.74          |

**Comment by coffeegoddd** [comment]
@reltuk __DOLT__
<table>
<TR><TH>comparing_percentages</TH>
</TR>
<TR><TD>100.000000 to 100.000000</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>result</TH>
<TH>total</TH>
</TR>
<TR><TD>861683e</TD>
<TD>ok</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>version</TH>
<TH>total_tests</TH>
</TR>
<TR><TD>861683e</TD>
<TD>5937471</TD>
</TR>
</table>
<table>
<TR><TH>correctness_percentage</TH>
</TR>
<TR><TD>100.0</TD>
</TR>
</table>

**Comment by coffeegoddd** [comment]
@reltuk __DOLT__
|      test_name      | from_latency_p95 | to_latency_p95 | percent_change |
|---------------------|------------------|----------------|----------------|
| tpcc-scale-factor-1 | 61.08            | 61.08          | 0.0            |


|      test_name      | from_server_name |           from_server_version            | from_tps | to_server_name |            to_server_version             | to_tps | percent_change |
|---------------------|------------------|------------------------------------------|----------|----------------|------------------------------------------|--------|----------------|
| tpcc-scale-factor-1 | dolt             | 235cd0a426260f4417da34b95c42976f0cd930da | 37.73    | dolt           | 861683edd65d275757e5c428f162c740cc32e809 | 37.44  | -0.77          |

File: go/libraries/doltcore/sqle/database_provider.go [hunk 1]
```diff
@@ -1079,6 +1139,12 @@ func (p *DoltDatabaseProvider) registerNewDatabase(ctx *sql.Context, name string
 	// Ensure any provider-supplied DB load params are applied before any lazy DB load occurs.
 	p.applyDBLoadParamsToEnv(newEnv)
 
+	ddb := newEnv.DoltDB(ctx)
```
Comment (zachmu) [inline go/libraries/doltcore/sqle/database_provider.go:1142]: These additional lines are a little mysterious here, not sure why they aren't in NewDatabase. Comment, or move?

**Review by zachmu — APPROVED** [review]
LGTM, seems pretty reasonable

File: go/libraries/doltcore/sqle/database_provider.go (hunk 1 above)
Comment (reltuk) [reply go/libraries/doltcore/sqle/database_provider.go:1142]: I will follow with a cleanup in another PR.
